"""add_last_scan_total_resources_to_repository

Revision ID: 0c41c130bf05
Revises: 820997f91dcb
Create Date: 2025-05-31 19:36:10.077015

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0c41c130bf05'
down_revision = '820997f91dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('last_scan_total_resources', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'last_scan_total_resources')
    # ### end Alembic commands ###
