"""Add EcosystemStats table for daily aggregation

Revision ID: 265415657ac3
Revises: a431674157c5
Create Date: 2025-06-02 17:16:14.619797

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '265415657ac3'
down_revision = 'a431674157c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecosystemstats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_repositories', sa.Integer(), nullable=False),
    sa.Column('active_repositories', sa.Integer(), nullable=False),
    sa.Column('repositories_with_resources', sa.Integer(), nullable=False),
    sa.Column('total_resources', sa.Integer(), nullable=False),
    sa.Column('active_resources', sa.Integer(), nullable=False),
    sa.Column('total_resource_events', sa.Integer(), nullable=False),
    sa.Column('resource_type_breakdown', sa.JSON(), nullable=True),
    sa.Column('popular_helm_charts', sa.JSON(), nullable=True),
    sa.Column('daily_created_resources', sa.Integer(), nullable=False),
    sa.Column('daily_modified_resources', sa.Integer(), nullable=False),
    sa.Column('daily_deleted_resources', sa.Integer(), nullable=False),
    sa.Column('total_stars', sa.Integer(), nullable=False),
    sa.Column('total_forks', sa.Integer(), nullable=False),
    sa.Column('total_watchers', sa.Integer(), nullable=False),
    sa.Column('total_open_issues', sa.Integer(), nullable=False),
    sa.Column('language_breakdown', sa.JSON(), nullable=True),
    sa.Column('popular_topics', sa.JSON(), nullable=True),
    sa.Column('repository_growth', sa.Integer(), nullable=False),
    sa.Column('resource_growth', sa.Integer(), nullable=False),
    sa.Column('star_growth', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('calculation_duration_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_ecosystem_stats_date')
    )
    op.create_index(op.f('ix_ecosystemstats_date'), 'ecosystemstats', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecosystemstats_date'), table_name='ecosystemstats')
    op.drop_table('ecosystemstats')
    # ### end Alembic commands ###
