"""add_kubernetes_resources_count_to_repository_metrics

Revision ID: da5d1e860c14
Revises: 0c41c130bf05
Create Date: 2025-05-31 19:42:04.514825

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'da5d1e860c14'
down_revision = '0c41c130bf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value to handle existing records
    op.add_column('repositorymetrics', sa.Column('kubernetes_resources_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositorymetrics', 'kubernetes_resources_count')
    # ### end Alembic commands ###
