"""initial

Revision ID: ea60b8e7bbfc
Revises:
Create Date: 2025-05-31 17:09:14.556621

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "ea60b8e7bbfc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "owner", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("topics", sa.JSON(), nullable=True),
        sa.Column(
            "license_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "default_branch",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("discovery_tags", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column(
            "sync_status",
            sa.Enum("PENDING", "SYNCING", "SUCCESS", "ERROR", name="syncstatus"),
            nullable=False,
            default="PENDING",
        ),
        sa.Column(
            "sync_error", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column(
            "working_directory_path",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("last_scan_at", sa.DateTime(), nullable=True),
        sa.Column(
            "scan_status",
            sa.Enum("PENDING", "SYNCING", "SUCCESS", "ERROR", name="syncstatus"),
            nullable=False,
            default="PENDING",
        ),
        sa.Column(
            "scan_error", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repository_full_name"), "repository", ["full_name"], unique=False
    )
    op.create_index(
        op.f("ix_repository_github_id"), "repository", ["github_id"], unique=True
    )
    op.create_index(
        op.f("ix_repository_last_scan_at"), "repository", ["last_scan_at"], unique=False
    )
    op.create_index(
        op.f("ix_repository_last_sync_at"), "repository", ["last_sync_at"], unique=False
    )
    op.create_index(op.f("ix_repository_owner"), "repository", ["owner"], unique=False)
    op.create_index(
        op.f("ix_repository_scan_status"), "repository", ["scan_status"], unique=False
    )
    op.create_index(
        op.f("ix_repository_sync_status"), "repository", ["sync_status"], unique=False
    )
    op.create_table(
        "resourcetrendsnapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_date", sa.DateTime(), nullable=False),
        sa.Column(
            "time_window", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "resource_kind",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "resource_api_version",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "chart_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "chart_version", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "chart_repository",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("total_instances", sa.Integer(), nullable=False),
        sa.Column("active_repositories", sa.Integer(), nullable=False),
        sa.Column("new_adoptions", sa.Integer(), nullable=False),
        sa.Column("removals", sa.Integer(), nullable=False),
        sa.Column("modifications_count", sa.Integer(), nullable=False),
        sa.Column("version_distribution", sa.JSON(), nullable=True),
        sa.Column("repository_breakdown", sa.JSON(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_chart_name"),
        "resourcetrendsnapshot",
        ["chart_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_chart_repository"),
        "resourcetrendsnapshot",
        ["chart_repository"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_chart_version"),
        "resourcetrendsnapshot",
        ["chart_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_resource_api_version"),
        "resourcetrendsnapshot",
        ["resource_api_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_resource_kind"),
        "resourcetrendsnapshot",
        ["resource_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_snapshot_date"),
        "resourcetrendsnapshot",
        ["snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_time_window"),
        "resourcetrendsnapshot",
        ["time_window"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcetrendsnapshot_total_instances"),
        "resourcetrendsnapshot",
        ["total_instances"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "kubernetesresource",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column(
            "api_version", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "namespace", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "file_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("resource_metadata", sa.JSON(), nullable=True),
        sa.Column("spec", sa.JSON(), nullable=True),
        sa.Column(
            "current_status",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("modification_count", sa.Integer(), nullable=False),
        sa.Column(
            "last_change_type",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=True,
        ),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_id",
            "api_version",
            "kind",
            "name",
            "namespace",
            name="uq_k8s_resource_per_repo",
        ),
    )
    op.create_index(
        op.f("ix_kubernetesresource_api_version"),
        "kubernetesresource",
        ["api_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresource_current_status"),
        "kubernetesresource",
        ["current_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresource_deleted_at"),
        "kubernetesresource",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresource_kind"), "kubernetesresource", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_kubernetesresource_name"), "kubernetesresource", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_kubernetesresource_namespace"),
        "kubernetesresource",
        ["namespace"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresource_repository_id"),
        "kubernetesresource",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "repositorymetrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("stars_count", sa.Integer(), nullable=False),
        sa.Column("forks_count", sa.Integer(), nullable=False),
        sa.Column("watchers_count", sa.Integer(), nullable=False),
        sa.Column("open_issues_count", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("pushed_at", sa.DateTime(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repositorymetrics_recorded_at"),
        "repositorymetrics",
        ["recorded_at"],
        unique=False,
    )
    op.create_table(
        "kubernetesresourcemetrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column(
            "chart_version", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "chart_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "chart_repository",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "source_revision",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("image_versions", sa.JSON(), nullable=True),
        sa.Column("replicas", sa.Integer(), nullable=True),
        sa.Column("reference_versions", sa.JSON(), nullable=True),
        sa.Column("resource_status", sa.JSON(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["kubernetesresource.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kubernetesresourcemetrics_chart_name"),
        "kubernetesresourcemetrics",
        ["chart_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcemetrics_chart_repository"),
        "kubernetesresourcemetrics",
        ["chart_repository"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcemetrics_chart_version"),
        "kubernetesresourcemetrics",
        ["chart_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcemetrics_recorded_at"),
        "kubernetesresourcemetrics",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcemetrics_source_revision"),
        "kubernetesresourcemetrics",
        ["source_revision"],
        unique=False,
    )
    op.create_table(
        "kubernetesresourcereference",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_resource_id", sa.Uuid(), nullable=False),
        sa.Column("source_repository_id", sa.Uuid(), nullable=False),
        sa.Column("target_resource_id", sa.Uuid(), nullable=True),
        sa.Column("target_repository_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reference_type",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column(
            "reference_path",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column(
            "target_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "target_namespace",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "target_kind", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "target_api_version",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("is_external_reference", sa.Boolean(), nullable=False),
        sa.Column("external_reference_details", sa.JSON(), nullable=True),
        sa.Column(
            "referenced_version",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_resource_id"], ["kubernetesresource.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_resource_id"], ["kubernetesresource.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_is_external_reference"),
        "kubernetesresourcereference",
        ["is_external_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_reference_type"),
        "kubernetesresourcereference",
        ["reference_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_referenced_version"),
        "kubernetesresourcereference",
        ["referenced_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_source_repository_id"),
        "kubernetesresourcereference",
        ["source_repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_target_kind"),
        "kubernetesresourcereference",
        ["target_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_target_name"),
        "kubernetesresourcereference",
        ["target_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_target_namespace"),
        "kubernetesresourcereference",
        ["target_namespace"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kubernetesresourcereference_target_repository_id"),
        "kubernetesresourcereference",
        ["target_repository_id"],
        unique=False,
    )
    op.create_table(
        "resourcelifecycleevent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resource_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "resource_namespace",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "resource_kind",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "resource_api_version",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "event_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("event_timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "file_hash_before",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column(
            "file_hash_after",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("resource_snapshot", sa.JSON(), nullable=True),
        sa.Column("changes_detected", sa.JSON(), nullable=True),
        sa.Column("sync_run_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["kubernetesresource.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resourcelifecycleevent_event_timestamp"),
        "resourcelifecycleevent",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcelifecycleevent_event_type"),
        "resourcelifecycleevent",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcelifecycleevent_repository_id"),
        "resourcelifecycleevent",
        ["repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcelifecycleevent_resource_api_version"),
        "resourcelifecycleevent",
        ["resource_api_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcelifecycleevent_resource_kind"),
        "resourcelifecycleevent",
        ["resource_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcelifecycleevent_resource_name"),
        "resourcelifecycleevent",
        ["resource_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resourcelifecycleevent_resource_namespace"),
        "resourcelifecycleevent",
        ["resource_namespace"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_resourcelifecycleevent_resource_namespace"),
        table_name="resourcelifecycleevent",
    )
    op.drop_index(
        op.f("ix_resourcelifecycleevent_resource_name"),
        table_name="resourcelifecycleevent",
    )
    op.drop_index(
        op.f("ix_resourcelifecycleevent_resource_kind"),
        table_name="resourcelifecycleevent",
    )
    op.drop_index(
        op.f("ix_resourcelifecycleevent_resource_api_version"),
        table_name="resourcelifecycleevent",
    )
    op.drop_index(
        op.f("ix_resourcelifecycleevent_repository_id"),
        table_name="resourcelifecycleevent",
    )
    op.drop_index(
        op.f("ix_resourcelifecycleevent_event_type"),
        table_name="resourcelifecycleevent",
    )
    op.drop_index(
        op.f("ix_resourcelifecycleevent_event_timestamp"),
        table_name="resourcelifecycleevent",
    )
    op.drop_table("resourcelifecycleevent")
    op.drop_index(
        op.f("ix_kubernetesresourcereference_target_repository_id"),
        table_name="kubernetesresourcereference",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcereference_target_namespace"),
        table_name="kubernetesresourcereference",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcereference_target_name"),
        table_name="kubernetesresourcereference",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcereference_target_kind"),
        table_name="kubernetesresourcereference",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcereference_source_repository_id"),
        table_name="kubernetesresourcereference",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcereference_referenced_version"),
        table_name="kubernetesresourcereference",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcereference_reference_type"),
        table_name="kubernetesresourcereference",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcereference_is_external_reference"),
        table_name="kubernetesresourcereference",
    )
    op.drop_table("kubernetesresourcereference")
    op.drop_index(
        op.f("ix_kubernetesresourcemetrics_source_revision"),
        table_name="kubernetesresourcemetrics",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcemetrics_recorded_at"),
        table_name="kubernetesresourcemetrics",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcemetrics_chart_version"),
        table_name="kubernetesresourcemetrics",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcemetrics_chart_repository"),
        table_name="kubernetesresourcemetrics",
    )
    op.drop_index(
        op.f("ix_kubernetesresourcemetrics_chart_name"),
        table_name="kubernetesresourcemetrics",
    )
    op.drop_table("kubernetesresourcemetrics")
    op.drop_index(
        op.f("ix_repositorymetrics_recorded_at"), table_name="repositorymetrics"
    )
    op.drop_table("repositorymetrics")
    op.drop_index(
        op.f("ix_kubernetesresource_repository_id"), table_name="kubernetesresource"
    )
    op.drop_index(
        op.f("ix_kubernetesresource_namespace"), table_name="kubernetesresource"
    )
    op.drop_index(op.f("ix_kubernetesresource_name"), table_name="kubernetesresource")
    op.drop_index(op.f("ix_kubernetesresource_kind"), table_name="kubernetesresource")
    op.drop_index(
        op.f("ix_kubernetesresource_deleted_at"), table_name="kubernetesresource"
    )
    op.drop_index(
        op.f("ix_kubernetesresource_current_status"), table_name="kubernetesresource"
    )
    op.drop_index(
        op.f("ix_kubernetesresource_api_version"), table_name="kubernetesresource"
    )
    op.drop_table("kubernetesresource")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_total_instances"),
        table_name="resourcetrendsnapshot",
    )
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_time_window"), table_name="resourcetrendsnapshot"
    )
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_snapshot_date"),
        table_name="resourcetrendsnapshot",
    )
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_resource_kind"),
        table_name="resourcetrendsnapshot",
    )
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_resource_api_version"),
        table_name="resourcetrendsnapshot",
    )
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_chart_version"),
        table_name="resourcetrendsnapshot",
    )
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_chart_repository"),
        table_name="resourcetrendsnapshot",
    )
    op.drop_index(
        op.f("ix_resourcetrendsnapshot_chart_name"), table_name="resourcetrendsnapshot"
    )
    op.drop_table("resourcetrendsnapshot")
    op.drop_index(op.f("ix_repository_sync_status"), table_name="repository")
    op.drop_index(op.f("ix_repository_scan_status"), table_name="repository")
    op.drop_index(op.f("ix_repository_owner"), table_name="repository")
    op.drop_index(op.f("ix_repository_last_sync_at"), table_name="repository")
    op.drop_index(op.f("ix_repository_last_scan_at"), table_name="repository")
    op.drop_index(op.f("ix_repository_github_id"), table_name="repository")
    op.drop_index(op.f("ix_repository_full_name"), table_name="repository")
    op.drop_table("repository")
    op.execute("drop type syncstatus")
    # ### end Alembic commands ###
