name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          body: |
            ## What's Changed
            
            ### Docker Images
            - Backend: `ghcr.io/${{ github.repository }}-backend:${{ github.ref_name }}`
            - Frontend: `ghcr.io/${{ github.repository }}-frontend:${{ github.ref_name }}`
            
            ### Installation
            ```bash
            # Pull the images
            docker pull ghcr.io/${{ github.repository }}-backend:${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository }}-frontend:${{ github.ref_name }}
            ```

  publish-images:
    needs: create-release
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
